### ISSUE TITLE
PROTOTIPO

### ISSUE THREAD

**Issue by mel-16** [SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-team-lmn#1]
[PROTOTIPO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-team-lmn/files/14301618/PROTOTIPO.pdf)

**Comment by ElisabetRD** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
